// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Y-ij6xMFcwchrQQsvFdP4PgQwTAY100',
    appId: '1:475900074053:web:10d41793d08a03d3192b2c',
    messagingSenderId: '475900074053',
    projectId: 'musicconnects-e8e68',
    authDomain: 'musicconnects-e8e68.firebaseapp.com',
    storageBucket: 'musicconnects-e8e68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLLgU6AYZmcyL-093rk42rB5Vnu1sLo44',
    appId: '1:475900074053:android:49c017e33775b70d192b2c',
    messagingSenderId: '475900074053',
    projectId: 'musicconnects-e8e68',
    storageBucket: 'musicconnects-e8e68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7ZC7-uM7HLej7claLiAEMEpBWca4KH-s',
    appId: '1:475900074053:ios:aa4f1f117028cbd5192b2c',
    messagingSenderId: '475900074053',
    projectId: 'musicconnects-e8e68',
    storageBucket: 'musicconnects-e8e68.appspot.com',
    iosBundleId: 'com.example.flutterProjects',
  );
}
